apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: store
          image: il/store:1
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent