apiVersion: v1
kind: Service
metadata:  
  name: store-svc
spec:
  selector:    
    app: store
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP